### PR TITLE
[JENKINS-41558] Remove pipeline-stage-view

### PR DESCRIPTION
**Pull request by daniel-beck**
[JENKINS-41558](https://issues.jenkins-ci.org/browse/JENKINS-41558) looks like a severe bug, open for 8 months without any progress or response, despite many votes and watchers.

Since this plugin seems quite optional for pipeline use, it seems easiest to just remove it from the aggregator to prevent future new installs of Jenkins (setup wizard) from getting it by default.

Batteries included? Your batteries are leaking.

@abayer @jglick @svanoort 
@rtyler

### CODE REVIEW

**Comment by daniel-beck** [comment]
As per discussion with @svanoort yesterday, I may be overestimating the severity of the issue for regular Jenkins use.

That said, this plugin is still included separately with the setup wizard (contrary to my initial comment) so this does not actually constitute removal (and https://github.com/jenkinsci/workflow-aggregator-plugin/pull/6 had no followup PR to core's wizard list as it should have). However, it does get downgraded to an optional component of Pipeline, similar to utility-steps, which seems a reasonable classification to me, critical bug or not.

Therefore leaving this open to invite further feedback.

**Comment by svanoort** [comment]
FYI the original bug that prompted this is well on the way to solution.  I am strongly against removing this because it is something most users still expect out of box, and I see a lot of people assuming Stage View is just provided by default with core pipeline plugins (rather than an add-on UI plugin).

**Comment by jglick** [comment]
> does removing it here also in effect remove it from the suggested plugins in a fresh install?

No. As previously mentioned:

> this plugin is still included separately with the setup wizard

I remain +1 on this PR.

**Comment by daniel-beck** [comment]
@abayer https://github.com/jenkinsci/jenkins/blob/71f849dd758576858ff51ed9642ae1d6b1f05c51/core/src/main/resources/jenkins/install/platform-plugins.json#L52

**Comment by rodrigc** [comment]
I agree with jglick and am +1 on this.

pipeline-stage-view came out in the early days when the workflow (now pipeline) was implemented for Jenkins and there was nothing else around to visualize pipelines.
Now that a lot of work has been put into Blue Ocean, installing pipeline-stage-view doesn't really help.

pipeline-stage-view has lagged behind Blue Ocean, and doesn't do very well at all in terms of
pipelines with parallel stages, or the history when the pipeline stages in between jobs.

If anything, the fact that there are two ways to visualize pipelines (pipeline-stage-view out of the box),
and Blue Ocean as an additional install, is confusing.

I am working in a startup now, and am heavily pushing internally for adoption of pipeline and Blue Ocean.  Removing cruft like pipeline-stage-view from the default pipeline install would make my task easier, because there is less crufty stuff out of the box to confuse my users.

**Comment by batmat** [comment]
I also agree that this PR should be merged. 
I fully understand Blue Ocean might not cover yet all that is provided by pipeline-stage-view, but given the development is stuck and likely bugs are not going to be fixed high priority, we shouldn't be installing it anymore in the full suite.

**Comment by daniel-beck** [comment]
Two years later and the bug remains unresolved.

I just don't care anymore.

**Comment by rodrigc** [comment]
3 people agreed with this PR, and one person disagreed.  The person who disagreed has left Cloudbees.  So why not just merge it?

**Comment by daniel-beck** [comment]
I don't maintain this.

**Comment by rodrigc** [comment]
Who maintains it?

**Comment by ChristianCiach** [comment]
> Who maintains it?

It'´s half a year later. I guess this answers your question.

**Comment by bitwiseman** [comment]
Reviving. 
The summary is this plugin would still be installed by default, but would be appropriately marked as not *required* to run pipeline.

Okay, does anyone object to this now?

**Comment by bitwiseman** [comment]
@jglick  
Are we waiting on https://github.com/jenkinsci/workflow-aggregator-plugin/pull/36 (and the long chain of related PRs)?

**Comment by jglick** [comment]
> Are we waiting on #36

No, if you approve we can go ahead.

**Comment by jglick** [comment]
https://github.com/jenkinsci/workflow-aggregator-plugin/releases/tag/workflow-aggregator-2.7

**Comment by timja** [comment]
Broken a few ATH tests:
https://ci.jenkins.io/blue/organizations/jenkins/Core%2Facceptance-test-harness/detail/PR-748/5/tests

**Comment by jglick** [comment]
https://github.com/jenkinsci/acceptance-test-harness/search?q=workflow-aggregator are all incorrect. Nothing should be referring to `workflow-aggregator`.

**Comment by timja** [comment]
https://github.com/jenkinsci/acceptance-test-harness/pull/748/commits/131d40216330a2df9d910501f0ef0002ecc7d627 adjusts failing tests. Still a couple more references to the aggregator but I ran out of time

**Comment by jglick** [comment]
Was that intended to be in some PR?

**Comment by timja** [comment]
It was in https://github.com/jenkinsci/acceptance-test-harness/pull/748, (noticed while iterating on that PR and just included it in)

**Pull request merged**
