### PR TITLE
Use DefaultGroovyMethods where helpful

### PR DESCRIPTION
**Pull request by jglick**
Picks up https://github.com/jenkinsci/workflow-cps-plugin/pull/143 since otherwise you get two branches running the same tests! Plan to pick up https://github.com/jenkinsci/workflow-cps-plugin/pull/139 when ready, so `scriptApproval.xml` can be deleted again.

@reviewbybees esp. @HRMPW

### CODE REVIEW

**Comment by HRMPW** [comment]
I was going to ask how long before [jenkinsci/workflow-cps-plugin#139](https://github.com/jenkinsci/workflow-cps-plugin/pull/139) is picked up but that will necessitate another bump in plugin version. This looks good in interim with the caveat that the new parallel syntax will be more opaque to non-groovy developers.  👍

**Comment by jglick** [comment]
> the new parallel syntax will be more opaque to non-groovy developers

Well, yeah. Pick your poison.

**Comment by abayer** [comment]
> the new parallel syntax will be more opaque to non-groovy developers

But way more awesome to me. =)

**Comment by HRMPW** [comment]
Yes, we should balance it with a Declarative Demo rather than "dumbing down" Scripted

**Pull request merged**
