### PR TITLE
Add lockable resources plugin to complement block-scoped stage

### PR DESCRIPTION
**Pull request by svanoort**
... since we're deprecated the concurrency setting along with the classic stage type, lockable resources should be included for feature parity.

### CODE REVIEW

**Comment by svanoort** [comment]
(waiting to see tests pass cleanly before submitting for review)

**Comment by jglick** [comment]
```
… org.jvnet.hudson.annotation_indexer.Index$2$1 fetch
WARNING: Failed to load org.jenkinsci.plugins.github_branch_source.GitHubSCMSource$DescriptorImpl
java.lang.NoClassDefFoundError: [Ljenkins/scm/api/SCMHeadCategory;
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2615)
	at java.lang.Class.getDeclaredMethods(Class.java:1860)
	at org.jvnet.hudson.annotation_indexer.Index$2$1.fetch(Index.java:102)
	at org.jvnet.hudson.annotation_indexer.Index$2$1.hasNext(Index.java:72)
	at org.jvnet.hudson.annotation_indexer.SubtypeIterator.fetch(SubtypeIterator.java:18)
	at org.jvnet.hudson.annotation_indexer.SubtypeIterator.hasNext(SubtypeIterator.java:28)
	at hudson.init.TaskMethodFinder.discoverTasks(TaskMethodFinder.java:56)
	at hudson.init.InitializerFinder.discoverTasks(InitializerFinder.java:33)
	at hudson.init.TaskMethodFinder.discoverTasks(TaskMethodFinder.java:32)
	at org.jvnet.hudson.reactor.TaskBuilder$2.discoverTasks(TaskBuilder.java:63)
	at org.jvnet.hudson.reactor.Reactor.<init>(Reactor.java:151)
	at org.jvnet.hudson.reactor.Reactor.<init>(Reactor.java:156)
	at jenkins.model.Jenkins$8.<init>(Jenkins.java:907)
	at jenkins.model.Jenkins.executeReactor(Jenkins.java:907)
	at jenkins.model.Jenkins.<init>(Jenkins.java:816)
	at hudson.model.Hudson.<init>(Hudson.java:83)
	at …
```

Are you going to fix this up?

**Comment by jglick** [comment]
Actually the error is not yours; corrected by https://github.com/jenkinsci/pipeline-github-lib-plugin/pull/1 and its inclusion here.

**Comment by jglick** [comment]
Please `git merge master` to proceed.

**Comment by svanoort** [comment]
@jglick Should be good now?

**Pull request merged**
